### ISSUE TITLE
Ghast in powered spawner

### ISSUE THREAD

**Issue by GreyRays1111** [Dmunch04/IndustrialReborn#1]
Ghast is not working properly. It cannot be killed by the player or mob sloughter

**Comment by Dmunch04** [comment]
Apologize for the late reply. I tested it myself, and can see the problem yes. I will look into this, and release the fix with the next version!

**Comment by Dmunch04** [comment]
Fixed in 7c67304

**Comment by GreyRays1111** [comment]
Ok
Your mod have some other issues:
1) Hillbillies don't gather in Soul Vial.
2) Also, overclocker upgrades do not work in Powered Spawner and Mob
Slaughter.


I'll wait for the update

чт, 11 апр. 2024 г., 12:29 Daniel Munch ***@***.***>:

**Comment by Dmunch04** [comment]
What exactly is hillbillies? Are they from another mod? And if so, which?
And overclocker (as well as other TR upgrades) aren't implemented to work with IR machines yet, but definitely planned!

**Comment by GreyRays1111** [comment]
Sorry. I mean vanilla villagers

чт, 11 апр. 2024 г., 23:46 Daniel Munch ***@***.***>:

**Comment by Dmunch04** [comment]
Problem has been fixed and will be included in next release
