### ISSUE TITLE
Blocks do not drop when broken

### ISSUE THREAD

**Issue by trunksbomb** [Dmunch04/IndustrialReborn#3]
The only block with a loot table currently is the Broken Spawner, so all other blocks in this mod do not drop as an item when you break them.

**Comment by Dmunch04** [comment]
As this mod is a [Tech Reborn](https://www.curseforge.com/minecraft/mc-mods/techreborn) addon, you should use Tech Reborn's wrench to pickup Industrial Reborn machines. Simply right-click while shifting to destroy the machine.

**Comment by trunksbomb** [comment]
Tech Reborn machines can be mined with a pickaxe. If this mod aims stay in line with the expected behavior of TR machines, then your machines should also be breakable with a pickaxe.

**Comment by trunksbomb** [comment]
https://github.com/Dmunch04/IndustrialReborn/assets/1904331/4c084dbe-955e-4f1b-b35d-cec2689facbb

**Comment by Dmunch04** [comment]
You are indeed right. Loot tables for machines will be added in next update
