### ISSUE TITLE
Mob Slaughter not generating drops for Blaze

### ISSUE THREAD

**Issue by DMCK96** [Dmunch04/IndustrialReborn#6]
Fabric Version: 0.14.25
Tech Reborn Version: 5.8.7
Industrial Reborn Version: 1.16.5-BETA
Minecraft Version: 1.20.1

I have it killing blaze's with the 'Mob Slaughter' and they are generating liquid exp but they are not generating any drops. 

Tested with skeletons and it was generating drops no problem.

Update: Could this be due to it requiring to be killed by a player to drop a blaze rod? Can we simulate a player kill or maybe a module to simulate a player kill to get around this issue?

**Comment by DMCK96** [comment]
I can see that you are using MOB_SLAUGHTER_INSTANT_KILL_BLACKLIST which switches to use player damage rather than setting their health to 0. 

You already have the functionality there to enable player-kill loot.

**Comment by Dmunch04** [comment]
Thank you for reporting the issue! You indeed right. Blade rods are only dropped when killed by a player, and so Blaze Will be added to MOB_SLAUGHTER_INSTANT_KILL_BLACKLIST

**Comment by DMCK96** [comment]
I've downloaded the backport branch and currently testing a version locally that only uses the player-damage mode of killing rather than the InstantKill method. 

It does work however rather than generating the loot and placing it into the connected chest, it's just dropping the loot on the floor.  Will tweak it further today and update you on progress. 

Bit rusty with Java, been primarily writing C# for the last few years 😋

**Comment by DMCK96** [comment]
I've tested it locally and my changes are working as intended. I've submitted a pull request and explained my changes here: 

https://github.com/Dmunch04/IndustrialReborn/pull/7/commits/5e366bb052456a1a436d0f9078df7360f7aeec81

**Comment by Dmunch04** [comment]
Thank you. Changes has been merged
