### ISSUE TITLE
powered spawner spawning from invalid nbt

### ISSUE THREAD

**Issue by Linguardium** [Dmunch04/IndustrialReborn#8]
https://github.com/Dmunch04/IndustrialReborn/blob/8e427bda7187dbea63b154cb4bb68028870dc662/src/main/java/me/munchii/industrialreborn/blockentity/PoweredSpawnerBlockEntity.java#L113-L127

getEntityFromNbt is intended to be used for a saved entity in the world or a structure, where it is being recreated from the nbt. Soul vial does not store the entire nbt, only the entity type. 

This creates issues with mobs like Orcs from Adventurez, for example.

a better option would be to do a lookup in the registry and spawn using the 
```
create(ServerWorld world, @Nullable NbtCompound itemNbt, @Nullable Consumer<T> afterConsumer, BlockPos pos, SpawnReason reason, boolean alignPosition, boolean invertY)
```
method call, which calls initialize and other things to ensure the entity is fully set up the way it would have been if spawned naturally.

**Comment by Dmunch04** [comment]
Thank you for catching this. Wasn't aware this was problematic. Issue should be fixed in efcb74a
